// <auto-generated />
using System;
using AnalyzerQC.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalyzerQC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524083555_RenameFileUrlToFileKey")]
    partial class RenameFileUrlToFileKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnalyzerQC.Analyzer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("serial_number");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("site_id");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("SiteId");

                    b.ToTable("analyzer", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.AssayLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("level");

                    b.Property<Guid>("LotId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lot_id");

                    b.Property<int>("ReagentId")
                        .HasColumnType("int")
                        .HasColumnName("reagent_id");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("ReagentId");

                    b.ToTable("assay_limit", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.AssayLimitParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AssayLimitId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assay_limit_id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<float>("LowerLimit")
                        .HasColumnType("float")
                        .HasColumnName("lower_limit");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int")
                        .HasColumnName("parameter_id");

                    b.Property<float>("Target")
                        .HasColumnType("float")
                        .HasColumnName("target");

                    b.Property<float>("UpperLimit")
                        .HasColumnType("float")
                        .HasColumnName("upper_limit");

                    b.HasKey("Id");

                    b.HasIndex("AssayLimitId");

                    b.HasIndex("ParameterId");

                    b.ToTable("assay_limit_parameter", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lot_code");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("LotCode")
                        .IsUnique();

                    b.ToTable("lot", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model_code");

                    b.Property<int>("ModelGroupId")
                        .HasColumnType("int")
                        .HasColumnName("model_group_id");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model_name");

                    b.HasKey("Id");

                    b.HasIndex("ModelCode")
                        .IsUnique();

                    b.HasIndex("ModelGroupId");

                    b.ToTable("model", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.ModelGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("ModelGroupCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model_group_code");

                    b.Property<string>("ModelGroupName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model_group_name");

                    b.HasKey("Id");

                    b.HasIndex("ModelGroupCode")
                        .IsUnique();

                    b.ToTable("model_group", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("parameter_code");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("parameter_name");

                    b.Property<string>("ParameterUnits")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("parameter_units");

                    b.HasKey("Id");

                    b.HasIndex("ParameterCode")
                        .IsUnique();

                    b.ToTable("parameter", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.QcUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalyzerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("analyzer_id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("time");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("upload_status");

                    b.Property<string>("UploadType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("upload_type");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzerId");

                    b.ToTable("qc_upload", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Reagent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Levels")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("levels");

                    b.Property<string>("ReagentCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reagent_code");

                    b.Property<string>("ReagentName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reagent_name");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReagentCode")
                        .IsUnique();

                    b.ToTable("reagent", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<float>("Frequency")
                        .HasColumnType("float")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int")
                        .HasColumnName("notification_type");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("site_code");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("site_name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("time_zone");

                    b.Property<string>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("working_days");

                    b.Property<string>("WorkingTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("working_time");

                    b.HasKey("Id");

                    b.HasIndex("SiteCode")
                        .IsUnique();

                    b.ToTable("site", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("LotReagent", b =>
                {
                    b.Property<Guid>("LotsId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReagentsId")
                        .HasColumnType("int");

                    b.HasKey("LotsId", "ReagentsId");

                    b.HasIndex("ReagentsId");

                    b.ToTable("lot_reagent", (string)null);
                });

            modelBuilder.Entity("ModelGroupReagent", b =>
                {
                    b.Property<int>("ModelGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("ReagentsId")
                        .HasColumnType("int");

                    b.HasKey("ModelGroupsId", "ReagentsId");

                    b.HasIndex("ReagentsId");

                    b.ToTable("model_group_reagent", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Analyzer", b =>
                {
                    b.HasOne("AnalyzerQC.Model", "Model")
                        .WithMany("Analyzers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalyzerQC.Site", "AssignedSite")
                        .WithMany("Analyzers")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedSite");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AnalyzerQC.AssayLimit", b =>
                {
                    b.HasOne("AnalyzerQC.Lot", "Lot")
                        .WithMany("AssayLimits")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalyzerQC.Reagent", "Reagent")
                        .WithMany("AssayLimits")
                        .HasForeignKey("ReagentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");

                    b.Navigation("Reagent");
                });

            modelBuilder.Entity("AnalyzerQC.AssayLimitParameter", b =>
                {
                    b.HasOne("AnalyzerQC.AssayLimit", "AssayLimit")
                        .WithMany("AssayLimitParameters")
                        .HasForeignKey("AssayLimitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalyzerQC.Parameter", "Parameter")
                        .WithMany("AssayLimitParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssayLimit");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("AnalyzerQC.Model", b =>
                {
                    b.HasOne("AnalyzerQC.ModelGroup", "ModelGroup")
                        .WithMany("Models")
                        .HasForeignKey("ModelGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelGroup");
                });

            modelBuilder.Entity("AnalyzerQC.QcUpload", b =>
                {
                    b.HasOne("AnalyzerQC.Analyzer", "Analyzer")
                        .WithMany("QcUpload")
                        .HasForeignKey("AnalyzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analyzer");
                });

            modelBuilder.Entity("LotReagent", b =>
                {
                    b.HasOne("AnalyzerQC.Lot", null)
                        .WithMany()
                        .HasForeignKey("LotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalyzerQC.Reagent", null)
                        .WithMany()
                        .HasForeignKey("ReagentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelGroupReagent", b =>
                {
                    b.HasOne("AnalyzerQC.ModelGroup", null)
                        .WithMany()
                        .HasForeignKey("ModelGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalyzerQC.Reagent", null)
                        .WithMany()
                        .HasForeignKey("ReagentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnalyzerQC.Analyzer", b =>
                {
                    b.Navigation("QcUpload");
                });

            modelBuilder.Entity("AnalyzerQC.AssayLimit", b =>
                {
                    b.Navigation("AssayLimitParameters");
                });

            modelBuilder.Entity("AnalyzerQC.Lot", b =>
                {
                    b.Navigation("AssayLimits");
                });

            modelBuilder.Entity("AnalyzerQC.Model", b =>
                {
                    b.Navigation("Analyzers");
                });

            modelBuilder.Entity("AnalyzerQC.ModelGroup", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AnalyzerQC.Parameter", b =>
                {
                    b.Navigation("AssayLimitParameters");
                });

            modelBuilder.Entity("AnalyzerQC.Reagent", b =>
                {
                    b.Navigation("AssayLimits");
                });

            modelBuilder.Entity("AnalyzerQC.Site", b =>
                {
                    b.Navigation("Analyzers");
                });
#pragma warning restore 612, 618
        }
    }
}
