// <auto-generated />
using System;
using AnalyzerQC.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalyzerQC.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301123533_Reagent")]
    partial class Reagent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnalyzerQC.Analyzer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("serial_number");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("site_id");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("SiteId");

                    b.ToTable("analyzer", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model_code");

                    b.Property<int>("ModelGroupId")
                        .HasColumnType("int")
                        .HasColumnName("model_group_id");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model_name");

                    b.HasKey("Id");

                    b.HasIndex("ModelCode")
                        .IsUnique();

                    b.HasIndex("ModelGroupId");

                    b.ToTable("model", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.ModelGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("ModelGroupCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model_group_code");

                    b.Property<string>("ModelGroupName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model_group_name");

                    b.HasKey("Id");

                    b.HasIndex("ModelGroupCode")
                        .IsUnique();

                    b.ToTable("model_group", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Reagent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Levels")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("levels");

                    b.Property<int>("ModelGroupId")
                        .HasColumnType("int")
                        .HasColumnName("model_group_id");

                    b.Property<string>("ReagentCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reagent_code");

                    b.Property<string>("ReagentName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reagent_name");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ModelGroupId");

                    b.ToTable("reagent", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<float>("Frequency")
                        .HasColumnType("float")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int")
                        .HasColumnName("notification_type");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("site_code");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("site_name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("time_zone");

                    b.Property<string>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("working_days");

                    b.Property<string>("WorkingTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("working_time");

                    b.HasKey("Id");

                    b.HasIndex("SiteCode")
                        .IsUnique();

                    b.ToTable("site", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeleterId")
                        .HasColumnType("longtext")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("AnalyzerQC.Analyzer", b =>
                {
                    b.HasOne("AnalyzerQC.Model", "Model")
                        .WithMany("Analyzers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalyzerQC.Site", "AssignedSite")
                        .WithMany("Analyzers")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedSite");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AnalyzerQC.Model", b =>
                {
                    b.HasOne("AnalyzerQC.ModelGroup", "ModelGroup")
                        .WithMany("Models")
                        .HasForeignKey("ModelGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelGroup");
                });

            modelBuilder.Entity("AnalyzerQC.Reagent", b =>
                {
                    b.HasOne("AnalyzerQC.ModelGroup", "ModelGroup")
                        .WithMany("Reagents")
                        .HasForeignKey("ModelGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelGroup");
                });

            modelBuilder.Entity("AnalyzerQC.Model", b =>
                {
                    b.Navigation("Analyzers");
                });

            modelBuilder.Entity("AnalyzerQC.ModelGroup", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Reagents");
                });

            modelBuilder.Entity("AnalyzerQC.Site", b =>
                {
                    b.Navigation("Analyzers");
                });
#pragma warning restore 612, 618
        }
    }
}
